# Generated by Django 3.2.12 on 2022-03-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('issued', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitdate', models.DateTimeField()),
                ('fine', models.FloatField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.issue')),
            ],
        ),
    ]
