# Generated by Django 3.2.12 on 2022-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='issue',
        ),
        migrations.AddField(
            model_name='submit',
            name='bookname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='issued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submit',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='bookname',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='branch',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='submit',
            name='fine',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='submitdate',
            field=models.DateTimeField(null=True),
        ),
    ]
