# Generated by Django 3.2.12 on 2022-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220325_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='bookname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
