# Generated by Django 3.2.12 on 2022-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220327_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issued',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='submitdate',
            field=models.DateTimeField(null=True),
        ),
    ]
